import type { CliCommandSpec } from "./cli-spec.ts"

export const CLI_VERSION = "0.2.0"

export const LIMIT_FLAGS: readonly string[] = [
  "max-agents",
  "max-concurrent",
  "schema-retry-limit",
  "max-work-items-per-agent",
  "max-inventory-items-returned",
  "max-prompt-bytes-per-agent",
  "max-mutation-files-per-agent",
  "max-mutation-files-per-run",
  "max-parallel-items",
  "max-pipeline-items",
  "max-tool-calls-per-agent",
  "max-tool-calls-per-run",
  "task-budget",
  "min-remaining-tokens-for-agent",
]

const RUN_FLAGS: readonly string[] = [
  "args",
  "journal",
  "provider",
  "mock",
  "budget",
  "approved",
  "json",
  "quiet",
  "no-input",
  "model",
  "model-policy",
  "codex-base-url",
  "codex-path-override",
  "codex-config",
  "skip-git-repo-check",
  "echo-prompts",
  "deterministic-timestamps",
  "run-id",
  "working-directory",
  "cwd",
  "workflow-permission-key",
  "background-worker",
  ...LIMIT_FLAGS,
]

const BACKGROUND_FLAGS: readonly string[] = [
  "background",
  "status-server",
  "status-host",
  "status-port",
]

export const FLAG_TYPES: ReadonlyMap<string, "boolean" | "string"> = new Map([
  ["args", "string"],
  ["journal", "string"],
  ["provider", "string"],
  ["mock", "boolean"],
  ["budget", "string"],
  ["approved", "boolean"],
  ["background", "boolean"],
  ["background-worker", "boolean"],
  ["status-server", "boolean"],
  ["status-host", "string"],
  ["status-port", "string"],
  ["json", "boolean"],
  ["quiet", "boolean"],
  ["no-input", "boolean"],
  ["event-limit", "string"],
  ["journal-root", "string"],
  ["limit", "string"],
  ["host", "string"],
  ["port", "string"],
  ["model", "string"],
  ["model-policy", "string"],
  ["codex-base-url", "string"],
  ["codex-path-override", "string"],
  ["codex-config", "string"],
  ["skip-git-repo-check", "boolean"],
  ["echo-prompts", "boolean"],
  ["deterministic-timestamps", "boolean"],
  ["run-id", "string"],
  ["goal", "string"],
  ["name", "string"],
  ["output", "string"],
  ["workflow-permission-key", "string"],
  ["working-directory", "string"],
  ["cwd", "string"],
  ["max-agents", "string"],
  ["max-concurrent", "string"],
  ["schema-retry-limit", "string"],
  ["max-work-items-per-agent", "string"],
  ["max-inventory-items-returned", "string"],
  ["max-prompt-bytes-per-agent", "string"],
  ["max-mutation-files-per-agent", "string"],
  ["max-mutation-files-per-run", "string"],
  ["max-parallel-items", "string"],
  ["max-pipeline-items", "string"],
  ["max-tool-calls-per-agent", "string"],
  ["max-tool-calls-per-run", "string"],
  ["task-budget", "string"],
  ["min-remaining-tokens-for-agent", "string"],
])

export const COMMANDS: readonly CliCommandSpec[] = [
  {
    name: "draft",
    summary: "Write a deterministic workflow scaffold.",
    usage: ["draft --goal '<goal>' [--name name] [--output .codex/workflows/name.ts] [--json]"],
    flags: ["goal", "name", "output", "cwd", "json", "quiet"],
    maxPositionals: Number.POSITIVE_INFINITY,
  },
  {
    name: "validate",
    summary: "Validate a workflow script.",
    usage: ["validate <script-or-name> --args '<json>' [--journal <path>] [--json] [--no-input]"],
    flags: RUN_FLAGS,
    maxPositionals: 1,
  },
  {
    name: "test",
    summary: "Run a workflow with the mock provider by default.",
    usage: ["test <script-or-name> --args '<json>' [--provider mock|sdk] [--budget small|standard|deep] [--json] [--no-input]"],
    flags: RUN_FLAGS,
    maxPositionals: 1,
  },
  {
    name: "workflow",
    summary: "Run a workflow with the live SDK provider by default.",
    usage: [
      "workflow <script-or-name> --args '<json>' [--journal <path>] [--provider sdk|mock] [--budget small|standard|deep] [--approved] [--json] [--no-input]",
      "workflow <script-or-name> --args '<json>' --background [--status-server] [--json] [--no-input]",
    ],
    flags: [...RUN_FLAGS, ...BACKGROUND_FLAGS],
    maxPositionals: 1,
  },
  {
    name: "run",
    summary: "Alias of workflow.",
    usage: ["run <script-or-name> --args '<json>' [--journal <path>] [--provider sdk|mock] [--budget small|standard|deep] [--approved] [--json] [--no-input]"],
    flags: [...RUN_FLAGS, ...BACKGROUND_FLAGS],
    maxPositionals: 1,
  },
  {
    name: "resume",
    summary: "Resume the latest or named journal.",
    usage: ["resume [--journal <path>] [--provider sdk|mock] [--approved] [--json] [--no-input]"],
    flags: [...RUN_FLAGS, ...BACKGROUND_FLAGS],
    maxPositionals: 1,
  },
  {
    name: "inspect",
    summary: "Print the full workflow snapshot projected from a journal.",
    usage: ["inspect [--journal <path>] [--json]"],
    flags: ["journal", "json", "quiet"],
    maxPositionals: 0,
  },
  {
    name: "status",
    summary: "Print a workflow status summary projected from a journal.",
    usage: ["status [--journal <path>] [--event-limit 5] [--json]"],
    flags: ["journal", "event-limit", "json", "quiet"],
    maxPositionals: 0,
  },
  {
    name: "list",
    summary: "List known workflow journals under the journal root.",
    usage: ["list [--journal-root .agent-loops-runs] [--limit 20] [--event-limit 5] [--json]"],
    flags: ["journal-root", "limit", "event-limit", "json", "quiet"],
    maxPositionals: 0,
  },
  {
    name: "serve",
    summary: "Serve a read-only live HTML status page for a journal.",
    usage: ["serve [--journal <path>] [--host 127.0.0.1] [--port 0] [--json]"],
    flags: ["journal", "host", "port", "json", "quiet"],
    maxPositionals: 0,
  },
  {
    name: "help",
    summary: "Show this help.",
    usage: ["help"],
    flags: ["json"],
    maxPositionals: 1,
  },
]
